openapi: "3.0.0"
info:
  title: appointment management api
  version: 1.0.0
paths:
  /api/v1/services:
    get:
      summary: get services detail
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/service"
        '404':
          description: service not found

    post:
      summary: create a new service
      security:
        - bearerAuth: []
      requestbody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                company_id:
                  type: string
                  format: uuid
                  description: the id of the company offering the service
                name:
                  type: string
                  description: the name of the service
                description:
                  type: string
                  description: the description of the service
                duration_in_sec:
                  type: int
                  description: the duration of the service in seconds
                price:
                  type: number
                  description: the price of the service
                active:
                  type: bool
      responses:
        '201':
          description: service created successfully
        '400':
          description: bad request

  /api/v1/services/{service_id}:
    put:
      summary: update service details by service id
      parameters:
        - name: service_id
          in: path
          required: true
          description: id of the service to update
          schema:
            type: string
            format: uuid
      requestbody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/service"
      responses:
        '200':
          description: successful operation
        '400':
          description: bad request
        '404':
          description: service not found

    get:
      summary: get service detail
      parameters:
        - name: service_id
          in: path
          required: true
          description: id of the service to update
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/service"
        '404':
          description: service not found

  /api/v1/appointments:
    post:
      summary: create a new appointment
      requestbody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AppointmentPost"
      responses:
        '201':
          description: appointment created successfully
        '400':
          description: bad request

  /api/v1/appointments/{appointment_id}:
    get:
      summary: get appointment details by appointment id
      parameters:
        - name: appointment_id
          in: path
          required: true
          description: id of the appointment to retrieve
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AppointmentGet"
        '404':
          description: appointment not found

    put:
      summary: update appointment details by appointment id
      parameters:
        - name: appointment_id
          in: path
          required: true
          description: id of the appointment to update
          schema:
            type: string
            format: uuid
        - name: service_id
          in: path
          required: true
          description: id of the service to update
          schema:
            type: string
            format: uuid
      requestbody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AppointmentPut"
      responses:
        '200':
          description: successful operation
        '400':
          description: bad request
        '404':
          description: appointment not found

    delete:
      summary: delete appointment by appointment id
      parameters:
        - name: appointment_id
          in: path
          required: true
          description: id of the appointment to delete
          schema:
            type: string
            format: uuid
        - name: service_id
          in: path
          required: true
          description: id of the service to update
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: appointment deleted successfully
        '404':
          description: appointment not found

  /api/v1/services/{service_id}/appointments/free:
    get:
      summary: Get free slots for a given day
      parameters:
        - name: date
          in: query
          description: "Optional date parameter (format: YYYY-MM-DD)"
          schema:
            type: string
          example: "2023-12-06"
        - name: service_id
          in: path
          required: true
          description: id of the service to update
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    employee_id:
                      type: string
                      format: uuid
                    slot_start_time:
                      type: string
                      format: date-time
                    slot_end_time:
                      type: string
                      format: date-time
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Not Found

  /api/v1/employee_schedules:
    get:
      summary: Get employee schedules
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/scheduleGet"
        '404':
          description: Employee schedules not found

    post:
      summary: Create a new employee schedule
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/schedulePost"
      responses:
        '201':
          description: Employee schedule created successfully
        '400':
          description: Bad request

components:
  schemas:
    service:
      type: object
      properties:
        service_id:
          type: string
          format: uuid
          readonly: true
          description: the unique identifier for a service
        company_id:
          type: string
          format: uuid
          description: the id of the company offering the service
        name:
          type: string
          description: the name of the service
        description:
          type: string
          description: the description of the service
        duration_in_sec:
          type: int
          description: the duration of the service in seconds
        price:
          type: number
          description: the price of the service
        active:
          type: boolean
          description: tells if the service is active

    AppointmentPost:
      type: object
      required:
        - client_id
        - client_name
        - employee_id
        - start_time
        - end_time
      properties:
        client_id:
          type: string
          format: uuid
          description: the id of the client for the appointment
        employee_id:
          type: string
          format: uuid
          description: the id of the employee handling the appointment
        client_name:
          type: string
          description: the name of the client
        start_time:
          type: string
          format: date-time
          description: the start time of the appointment
        end_time:
          type: string
          format: date-time
          description: the end time of the appointment

    AppointmentPut:
      type: object
      required:
      properties:
        start_time:
          type: string
          format: date-time
          description: the start time of the appointment
        end_time:
          type: string
          format: date-time
          description: the end time of the appointment
        client_name:
          type: string
          description: the name of the client
        employee_id:
          type: string
          format: uuid
          description: the id of the employee handling the appointment

    AppointmentGet:
      type: object

      required:
        - service_id
        - client_id
        - client_name
        - employee_id
        - start_time
        - end_time
        - price_expected
        - canceled
        - served
      properties:
        service_id:
          type: string
          format: uuid
          description: the id of the service associated with the appointment
        created_at:
          type: string
          format: date-time
          readonly: true
          description: the timestamp when the appointment was created
        updated_at:
          type: string
          format: date-time
          readonly: true
          description: the timestamp when the appointment was last updated
        client_id:
          type: string
          format: uuid
          description: the id of the client for the appointment
        employee_id:
          type: string
          format: uuid
          description: the id of the employee handling the appointment
        client_name:
          type: string
          description: the name of the client
        start_time:
          type: string
          format: date-time
          description: the start time of the appointment
        end_time:
          type: string
          format: date-time
          description: the end time of the appointment
        price_expected:
          type: number
          format: decimal
          description: the expected price for the service
        price_final:
          type: number
          format: decimal
          description: the final price for the service
        discount:
          type: number
          description: the discount applied to the service price
        canceled:
          type: boolean
          description: indicates whether the appointment has been canceled
        cancellation_reason:
          type: string
          description: the reason for canceling the appointment
        provided:
          type: boolean
          description: indicates whether the service has been provided

    schedulePost:
      type: object
      properties:
        employee_id:
          type: string
          format: uuid
          description: The ID of the employee
        service_id:
          type: string
          format: uuid
          description: The ID of the service
        start_shift:
          type: string
          format: time
          description: The start shift time
        end_shift:
          type: string
          format: time
          description: The end shift time

    scheduleGet:
      type: object
      properties:
        schedule_id:
          type: string
          format: uuid
        service_id:
          type: string
          format: uuid
        employee_id:
          type: string
          format: uuid
        start_shift:
          type: string
          format: time
          description: The start shift time
        end_shift:
          type: string
          format: time
          description: The end shift time
