openapi: 3.0.0
info:
  title: Authentication and Authorization API
  version: 1.0.0
paths:
  /auth/login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  type: 
                    type: string
                    enum: [Bearer]
        '401':
          description: Unauthorized

  /auth/access:
    get:
      summary: Refresh JWT token
      requestBody:
        required: true
        content:
      security:
        - JWT
      responses:
        '200':
          description: Access control
          content:
            application/json:
              schema:
                type: object
                properties:
                  email: 
                    type: string
                    format: email
                  id: 
                    type: string
                    format: UUID
                  role:
                    type: string
                    enum: [admin, regular]


        '400':
          description: Bad request, authorization header is malformed or missing
        '401':
          description: Unauthorized
        '403':
          description: Unauthenticated

components:
  securitySchemes:
    JWT:
      type: apiKey
      in: header
      name: Authorization
      description: "Bearer {token}"
